class CountryEmergencyNumbers {
  final String country;
  final String countryCode;
  final String police;
  final String ambulance;
  final String generalEmergency;

  CountryEmergencyNumbers({
    required this.country,
    required this.countryCode,
    required this.police,
    required this.ambulance,
    required this.generalEmergency,
  });

  static final List<CountryEmergencyNumbers> countries = [
    CountryEmergencyNumbers(country: 'India', countryCode: 'IN', police: '100', ambulance: '102 / 108', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'United States', countryCode: 'US', police: '911', ambulance: '911', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'United Kingdom', countryCode: 'UK', police: '999', ambulance: '999', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Canada', countryCode: 'CA', police: '911', ambulance: '911', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'Australia', countryCode: 'AU', police: '000', ambulance: '000', generalEmergency: '000'),
    CountryEmergencyNumbers(country: 'Russia', countryCode: 'RU', police: '102', ambulance: '103', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'China', countryCode: 'CN', police: '110', ambulance: '120', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Brazil', countryCode: 'BR', police: '190', ambulance: '192', generalEmergency: '190'),
    CountryEmergencyNumbers(country: 'Germany', countryCode: 'DE', police: '110', ambulance: '112', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'France', countryCode: 'FR', police: '17', ambulance: '15', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Italy', countryCode: 'IT', police: '112', ambulance: '118', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Spain', countryCode: 'ES', police: '091', ambulance: '061', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Japan', countryCode: 'JP', police: '110', ambulance: '119', generalEmergency: '119'),
    CountryEmergencyNumbers(country: 'South Korea', countryCode: 'KR', police: '112', ambulance: '119', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'South Africa', countryCode: 'ZA', police: '10111', ambulance: '10177', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Mexico', countryCode: 'MX', police: '911', ambulance: '911', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'Indonesia', countryCode: 'ID', police: '110', ambulance: '118', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Pakistan', countryCode: 'PK', police: '15', ambulance: '115', generalEmergency: '1122'),
    CountryEmergencyNumbers(country: 'Bangladesh', countryCode: 'BD', police: '999', ambulance: '999', generalEmergency: '999'),
    CountryEmergencyNumbers(country: 'Nepal', countryCode: 'NP', police: '100', ambulance: '102', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Sri Lanka', countryCode: 'LK', police: '119', ambulance: '110', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'UAE', countryCode: 'AE', police: '999', ambulance: '998', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Saudi Arabia', countryCode: 'SA', police: '999', ambulance: '997', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'Turkey', countryCode: 'TR', police: '155', ambulance: '112', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Israel', countryCode: 'IL', police: '100', ambulance: '101', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Egypt', countryCode: 'EG', police: '122', ambulance: '123', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Nigeria', countryCode: 'NG', police: '112', ambulance: '112', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Kenya', countryCode: 'KE', police: '999', ambulance: '999', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Argentina', countryCode: 'AR', police: '101', ambulance: '107', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'Chile', countryCode: 'CL', police: '133', ambulance: '131', generalEmergency: '131'),
    CountryEmergencyNumbers(country: 'Colombia', countryCode: 'CO', police: '112', ambulance: '125', generalEmergency: '165'),
    CountryEmergencyNumbers(country: 'Peru', countryCode: 'PE', police: '105', ambulance: '106', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'Venezuela', countryCode: 'VE', police: '171', ambulance: '171', generalEmergency: '171'),
    CountryEmergencyNumbers(country: 'Thailand', countryCode: 'TH', police: '191', ambulance: '1669', generalEmergency: '191'),
    CountryEmergencyNumbers(country: 'Malaysia', countryCode: 'MY', police: '999', ambulance: '999', generalEmergency: '999'),
    CountryEmergencyNumbers(country: 'Singapore', countryCode: 'SG', police: '999', ambulance: '995', generalEmergency: '999'),
    CountryEmergencyNumbers(country: 'Philippines', countryCode: 'PH', police: '911', ambulance: '911', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'Vietnam', countryCode: 'VN', police: '113', ambulance: '115', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'New Zealand', countryCode: 'NZ', police: '111', ambulance: '111', generalEmergency: '111'),
    CountryEmergencyNumbers(country: 'Netherlands', countryCode: 'NL', police: '112', ambulance: '112', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Belgium', countryCode: 'BE', police: '101', ambulance: '112', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Switzerland', countryCode: 'CH', police: '117', ambulance: '144', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Austria', countryCode: 'AT', police: '133', ambulance: '144', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Sweden', countryCode: 'SE', police: '112', ambulance: '112', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Norway', countryCode: 'NO', police: '112', ambulance: '113', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Denmark', countryCode: 'DK', police: '114', ambulance: '112', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Finland', countryCode: 'FI', police: '112', ambulance: '112', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Poland', countryCode: 'PL', police: '997', ambulance: '999', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Czech Republic', countryCode: 'CZ', police: '158', ambulance: '155', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Hungary', countryCode: 'HU', police: '107', ambulance: '104', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Greece', countryCode: 'GR', police: '100', ambulance: '166', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Portugal', countryCode: 'PT', police: '112', ambulance: '112', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Ireland', countryCode: 'IE', police: '999', ambulance: '999', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Iceland', countryCode: 'IS', police: '112', ambulance: '112', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Ukraine', countryCode: 'UA', police: '102', ambulance: '103', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Belarus', countryCode: 'BY', police: '102', ambulance: '103', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Kazakhstan', countryCode: 'KZ', police: '102', ambulance: '103', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Uzbekistan', countryCode: 'UZ', police: '102', ambulance: '103', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Afghanistan', countryCode: 'AF', police: '119', ambulance: '102', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Iran', countryCode: 'IR', police: '110', ambulance: '115', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Iraq', countryCode: 'IQ', police: '104', ambulance: '122', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Qatar', countryCode: 'QA', police: '999', ambulance: '999', generalEmergency: '999'),
    CountryEmergencyNumbers(country: 'Kuwait', countryCode: 'KW', police: '112', ambulance: '112', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Oman', countryCode: 'OM', police: '9999', ambulance: '9999', generalEmergency: '9999'),
    CountryEmergencyNumbers(country: 'Morocco', countryCode: 'MA', police: '19', ambulance: '15', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Algeria', countryCode: 'DZ', police: '1548', ambulance: '14', generalEmergency: '14'),
    CountryEmergencyNumbers(country: 'Tunisia', countryCode: 'TN', police: '197', ambulance: '190', generalEmergency: '190'),
    CountryEmergencyNumbers(country: 'Ethiopia', countryCode: 'ET', police: '991', ambulance: '907', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'Ghana', countryCode: 'GH', police: '191', ambulance: '193', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Tanzania', countryCode: 'TZ', police: '112', ambulance: '114', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Uganda', countryCode: 'UG', police: '999', ambulance: '912', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Zimbabwe', countryCode: 'ZW', police: '995', ambulance: '994', generalEmergency: '999'),
    CountryEmergencyNumbers(country: 'Botswana', countryCode: 'BW', police: '999', ambulance: '997', generalEmergency: '999'),
    CountryEmergencyNumbers(country: 'Namibia', countryCode: 'NA', police: '10111', ambulance: '2032276', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Angola', countryCode: 'AO', police: '113', ambulance: '118', generalEmergency: '110'),
    CountryEmergencyNumbers(country: 'Cambodia', countryCode: 'KH', police: '117', ambulance: '119', generalEmergency: '118'),
    CountryEmergencyNumbers(country: 'Laos', countryCode: 'LA', police: '191', ambulance: '195', generalEmergency: '190'),
    CountryEmergencyNumbers(country: 'Myanmar', countryCode: 'MM', police: '199', ambulance: '192', generalEmergency: '999'),
    CountryEmergencyNumbers(country: 'Mongolia', countryCode: 'MN', police: '102', ambulance: '103', generalEmergency: '105'),
    CountryEmergencyNumbers(country: 'North Korea', countryCode: 'KP', police: '119', ambulance: '119', generalEmergency: '119'),
    CountryEmergencyNumbers(country: 'Bolivia', countryCode: 'BO', police: '110', ambulance: '118', generalEmergency: '118'),
    CountryEmergencyNumbers(country: 'Paraguay', countryCode: 'PY', police: '911', ambulance: '141', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'Uruguay', countryCode: 'UY', police: '911', ambulance: '105', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'Ecuador', countryCode: 'EC', police: '911', ambulance: '911', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'Panama', countryCode: 'PA', police: '104', ambulance: '103', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'Costa Rica', countryCode: 'CR', police: '911', ambulance: '911', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'Cuba', countryCode: 'CU', police: '106', ambulance: '104', generalEmergency: '106'),
    CountryEmergencyNumbers(country: 'Haiti', countryCode: 'HT', police: '114', ambulance: '118', generalEmergency: '114'),
    CountryEmergencyNumbers(country: 'Dominican Republic', countryCode: 'DO', police: '911', ambulance: '911', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'Jamaica', countryCode: 'JM', police: '119', ambulance: '110', generalEmergency: '119'),
    CountryEmergencyNumbers(country: 'Fiji', countryCode: 'FJ', police: '917', ambulance: '911', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'Papua New Guinea', countryCode: 'PG', police: '112', ambulance: '111', generalEmergency: '111'),
    CountryEmergencyNumbers(country: 'Maldives', countryCode: 'MV', police: '119', ambulance: '102', generalEmergency: '911'),
    CountryEmergencyNumbers(country: 'Bhutan', countryCode: 'BT', police: '113', ambulance: '112', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Brunei', countryCode: 'BN', police: '993', ambulance: '991', generalEmergency: '991'),
    CountryEmergencyNumbers(country: 'Seychelles', countryCode: 'SC', police: '999', ambulance: '151', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Mauritius', countryCode: 'MU', police: '999', ambulance: '114', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Madagascar', countryCode: 'MG', police: '117', ambulance: '124', generalEmergency: '112'),
    CountryEmergencyNumbers(country: 'Sudan', countryCode: 'SD', police: '999', ambulance: '333', generalEmergency: '999'),
    CountryEmergencyNumbers(country: 'Libya', countryCode: 'LY', police: '1515', ambulance: '193', generalEmergency: '1515'),
  ];

  static CountryEmergencyNumbers getByCountry(String countryName) {
    return countries.firstWhere(
      (c) => c.country.toLowerCase() == countryName.toLowerCase(),
      orElse: () => countries.first,
    );
  }

  static CountryEmergencyNumbers getByCode(String code) {
    return countries.firstWhere(
      (c) => c.countryCode.toLowerCase() == code.toLowerCase(),
      orElse: () => countries.first,
    );
  }
}
